#!/bin/bash
# Shell script to backup MySql database
# To backup Nysql databases file to db//backups dir and later pick up by your
# script. You can skip few databases from backup too.

DB="muamely"
USER="mml"
PASS="Mu@mely1"


# Linux bin paths, change this if it can not be autodetected via which command
MYSQLDUMP="$(which mysqldump)"
GZIP="$(which gzip)"

# Backup Dest directory, change this if you have someother location
DEST="/home/rails/muamely.com/db/backups"

# Get data in dd-mm-yyyy format
NOW="$(date +'%Y-%m-%d-%H-%M-%S')"

# File to store current backup file
FILE=""
# Store list of databases
FILE="$DEST/$DB.$NOW.sql.gz"
# do all inone job in pipe,
# connect to mysql using mysqldump for select mysql database
# and pipe it out to gz file in backup dir :)
$MYSQLDUMP -u $USER -p$PASS $DB | $GZIP -9 > $FILE